when:
  - event: pull_request
    branch: main
    path:
      include:
        - backend/**
        - .woodpecker/backend-check.yaml
        - .woodpecker/check.yaml
      on_empty: false
  - event: push
    branch: main
    path:
      include:
        - backend/**
        - .woodpecker/backend-check.yaml
        - .woodpecker/check.yaml
      on_empty: false

steps:
  - name: backend check
    image: rust:1.95
    directory: backend
    commands:
      - curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C /usr/local/cargo/bin
      - rustup component add rustfmt
      - rustup component add clippy
      - cargo fmt -- --check
      - cargo clippy --all-targets --all-features -- -D warnings
      - cargo check
      - cargo nextest run --profile ci
