when:
  - event: push
    branch:
      - main
      - woodpecker
    path:
      include:
        - backend/**
        - .woodpecker/backend-image.yaml
      exclude:
        - backend/docker/**
      on_empty: false

variables:
  - image_prefix: &image_prefix ghcr.io/wetty-technology/wetty-chat-backend
  - builder_repo: &builder_repo ghcr.io/wetty-technology/wetty-chat-backend-builder-base
  - builder_tag: &builder_tag rust-1.95.0-trixie
  - runtime_image: &runtime_image ghcr.io/wetty-technology/wetty-chat-backend-runtime-base:trixie

steps:
  - name: build and push
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      repo: *image_prefix
      registry: ghcr.io
      dockerfile: backend/Dockerfile
      context: backend
      platforms: linux/amd64,linux/arm64
      provenance: false
      tags:
        - ${CI_COMMIT_SHA}
        - latest
      build_args:
        BUILDER_BASE_REPOSITORY: *builder_repo
        BUILDER_BASE_TAG: *builder_tag
        RUNTIME_BASE_IMAGE: *runtime_image
      cache_from:
        - type=registry\,ref=ghcr.io/wetty-technology/wetty-chat-backend:buildcache
      cache_to: type=registry\,ref=ghcr.io/wetty-technology/wetty-chat-backend:buildcache\,mode=max
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
