when:
  - event: pull_request
    branch: main
    path:
      include:
        - wetty-chat-mobile/**
        - .woodpecker/frontend-check.yaml
        - .woodpecker/check.yaml
      on_empty: false
  - event: push
    branch: main
    path:
      include:
        - wetty-chat-mobile/**
        - .woodpecker/frontend-check.yaml
        - .woodpecker/check.yaml
      on_empty: false

steps:
  - name: install
    image: node:22-bookworm
    directory: wetty-chat-mobile
    commands:
      - npm ci

  - name: format
    image: node:22-bookworm
    directory: wetty-chat-mobile
    depends_on:
      - install
    commands:
      - npm run format:ci

  - name: typecheck
    image: node:22-bookworm
    directory: wetty-chat-mobile
    depends_on:
      - install
    commands:
      - npm run typecheck

  - name: lint
    image: node:22-bookworm
    directory: wetty-chat-mobile
    depends_on:
      - install
    commands:
      - npm run lint

  - name: lingui
    image: node:22-bookworm
    directory: wetty-chat-mobile
    depends_on:
      - format
      - typecheck
      - lint
    commands:
      - npm run lingui:extract
      - npm run lingui:compile

  - name: test
    image: node:22-bookworm
    directory: wetty-chat-mobile
    depends_on:
      - lingui
    commands:
      - npm run test:run
